### ISSUE TITLE
Segfault when using ibuffalo faux snes controller

### ISSUE THREAD

**Issue by Elronnd** [StapleButter/melonDS#233]
I'm trying to use the ibufallo faux snes conltroller with melonds, but when I go to config->input config and select one of the things on joystick, after pressing a button on the controller, one of two things happens.  Either it registers that input fine, (e.g. it says button 1 for A), but when I press on B, it automatically reads in button 1 again, same for x/y/up/down/whatever/else.  Or, it segfaults.  Here's the traceback (with `-g3 -Og`).  Not very useful, I know:

```
#0  0x0000000000000000 in  ()
#1  0x00007ffff764139e in  () at /usr/lib/libgtk-3.so.0
#2  0x00007ffff7626ae2 in  () at /usr/lib/libgtk-3.so.0
#3  0x00007ffff764fc85 in  () at /usr/lib/libgtk-3.so.0
#4  0x00007ffff763ad7d in  () at /usr/lib/libgtk-3.so.0
#5  0x00007ffff764fbc0 in  () at /usr/lib/libgtk-3.so.0
#6  0x00007ffff763d38d in  () at /usr/lib/libgtk-3.so.0
#7  0x00007ffff763c145 in  () at /usr/lib/libgtk-3.so.0
#8  0x00007ffff763cf25 in  () at /usr/lib/libgtk-3.so.0
#9  0x00007ffff763cf3b in  () at /usr/lib/libgtk-3.so.0
#10 0x00007ffff763cf3b in  () at /usr/lib/libgtk-3.so.0
#11 0x00007ffff763cf3b in  () at /usr/lib/libgtk-3.so.0
#12 0x00007ffff763cf3b in  () at /usr/lib/libgtk-3.so.0
#13 0x00007ffff763cf3b in  () at /usr/lib/libgtk-3.so.0
#14 0x00007ffff763cf3b in  () at /usr/lib/libgtk-3.so.0
#15 0x00007ffff763cf3b in  () at /usr/lib/libgtk-3.so.0
#16 0x00007ffff763cf3b in  () at /usr/lib/libgtk-3.so.0
#17 0x00007ffff763cf3b in  () at /usr/lib/libgtk-3.so.0
#18 0x00007ffff7623128 in  () at /usr/lib/libgtk-3.so.0
#19 0x00007ffff5e03c5d in g_closure_invoke () at /usr/lib/libgobject-2.0.so.0
#20 0x00007ffff5e17b50 in  () at /usr/lib/libgobject-2.0.so.0
#21 0x00007ffff5e20806 in g_signal_emit_valist () at /usr/lib/libgobject-2.0.so.0
#22 0x00007ffff5e21240 in g_signal_emit () at /usr/lib/libgobject-2.0.so.0
#23 0x00007ffff720428f in  () at /usr/lib/libgdk-3.so.0
#24 0x00007ffff71eeac3 in  () at /usr/lib/libgdk-3.so.0
#25 0x00007ffff5b2a783 in  () at /usr/lib/libglib-2.0.so.0
#26 0x00007ffff5b29ca6 in g_main_context_dispatch () at /usr/lib/libglib-2.0.so.0
#27 0x00007ffff5b2a081 in  () at /usr/lib/libglib-2.0.so.0
#28 0x00007ffff5b2a3b2 in g_main_loop_run () at /usr/lib/libglib-2.0.so.0
#29 0x00007ffff76f0eff in gtk_main () at /usr/lib/libgtk-3.so.0
#30 0x0000555555596681 in main(int, char**) (argc=<optimized out>, argv=<optimized out>)
    at /home/elronnd/melonds/src/libui_sdl/main.cpp:1231
```

**Comment by StapleButter** [comment]
should be fixed
